apiVersion: v1
kind: Service
metadata:
  name: service-task-manager
  namespace: task-manager

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

  type: ClusterIP

  selector:
    app: task-manager
